stages:
  train:
    cmd: python model.py
    deps:
    - data
    - model.py
    outs:
    - model.pkl
    metrics:
    - metrics.csv:
        cache: false

plots:
  - metrics.csv:
      x: metrics
      y: values
      template: simple
      title: "Model Metrics"
      x_label: "Metric"
      y_label: "Value"


